### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by rogierslag** [inventid/maily#16]
While working on #15 I realized our version was a bit ad-hoc, complicated, and possibly non-understandable for anyone not actively working on the project.

Therefore I suggest to move to another versioning scheme. Right now we stay up-to-date with [`mjml`](https://github.com/mjmlio/mjml) versions, but that gets quickly annoying as it does not allow our API to evolve itself, without resorting to `-1` hacks. Those have broken backwards compatibility in the past! Not a good netizen so to say.

I therefore wanted to propose the following:

1. Major updates to MJML or React bump our major version number
1. Any API breaking update bumps our major version number
1. Minor and patch updates of React or MJML update the respective number as well
1. New features in Maily update the minor version number

In order to make this effective at a godo cut-off point, I'd suggest to move to `5.0.0` once #15 is merged.

@alexkolpa @alexwalterbos @wouter-willems @joostverdoorn @steffansluis: What is your take on this?

**Comment by AlexKolpa** [comment]
Sounds like a good approach to me! Trying to keep your own versioning in line with multiple other dependencies is indeed not the best approach, so I'd say let this project evolve on its own :+1:
